In [28]:
import sqlite3
import pandas as pd

con=sqlite3.connect('C:\\Users\\moham\\OneDrive\\Desktop\\SEM 3 OJT\\Proj_3.1\\data\\raw\\ipl.db')
def q(sql):
    return pd.read_sql(sql, con)

In [29]:
def run_sql_file(path):
    with open(path,'r') as f:
        script =f.read()
    con.executescript(script)
    con.commit()
    print('ran',path)

In [30]:
run_sql_file(r"C:\Users\moham\OneDrive\Desktop\SEM 3 OJT\Proj_3.1\sql\01_nulls_and_blanks.sql")

ran C:\Users\moham\OneDrive\Desktop\SEM 3 OJT\Proj_3.1\sql\01_nulls_and_blanks.sql

In [31]:
run_sql_file(r"C:\Users\moham\OneDrive\Desktop\SEM 3 OJT\Proj_3.1\sql\02_merge_categories.sql")

ran C:\Users\moham\OneDrive\Desktop\SEM 3 OJT\Proj_3.1\sql\02_merge_categories.sql

In [32]:
run_sql_file(r"C:\Users\moham\OneDrive\Desktop\SEM 3 OJT\Proj_3.1\sql\03_venue_names.sql")

ran C:\Users\moham\OneDrive\Desktop\SEM 3 OJT\Proj_3.1\sql\03_venue_names.sql

In [33]:
q("""Select venue_clean,Count(*) AS matches
from  v_matches_venue
GROUP BY venue_clean
ORDER BY matches DESC limit 5;""")

                          venue_clean  matches
0                    Wankhede Stadium      130
1                        Eden Gardens      104
2              MA Chidambaram Stadium       95
3               M Chinnaswamy Stadium       89
4  Rajiv Gandhi International Stadium       87

In [34]:
run_sql_file(r"C:\Users\moham\OneDrive\Desktop\SEM 3 OJT\Proj_3.1\sql\04_dedupe_venues.sql")

ran C:\Users\moham\OneDrive\Desktop\SEM 3 OJT\Proj_3.1\sql\04_dedupe_venues.sql

In [35]:
run_sql_file(r"C:\Users\moham\OneDrive\Desktop\SEM 3 OJT\Proj_3.1\sql\04_dedupe_venues.sql")

ran C:\Users\moham\OneDrive\Desktop\SEM 3 OJT\Proj_3.1\sql\04_dedupe_venues.sql

In [36]:
q("""Select count (*),venue,city
from venues
Group by venue
order by count(*) DESC
limit 10;""")

   count (*)                                              venue       city
0          2                            Sharjah Cricket Stadium        NaN
1          2  Maharaja Yadavindra Singh International Cricke...     Mohali
2          2                Dubai International Cricket Stadium        NaN
3          2                 Dr DY Patil Sports Academy, Mumbai     Mumbai
4          1                   Zayed Cricket Stadium, Abu Dhabi  Abu Dhabi
5          1                           Wankhede Stadium, Mumbai     Mumbai
6          1                                   Wankhede Stadium     Mumbai
7          1       Vidarbha Cricket Association Stadium, Jamtha     Nagpur
8          1                                    SuperSport Park  Centurion
9          1                         Subrata Roy Sahara Stadium       Pune

In [37]:
q("""Select count(*)As rows,COUNT(DISTINCT venue) AS names
FROM v_venues_clean;
""")

   rows  names
0    59     59

In [38]:
q("""select count(*),venue,city
from v_venues_clean
group by venue
order by count(*) desc
limit 10;""")

   count(*)                                             venue            city
0         1                  Zayed Cricket Stadium, Abu Dhabi       Abu Dhabi
1         1                          Wankhede Stadium, Mumbai          Mumbai
2         1                                  Wankhede Stadium          Mumbai
3         1      Vidarbha Cricket Association Stadium, Jamtha          Nagpur
4         1                                   SuperSport Park       Centurion
5         1                        Subrata Roy Sahara Stadium            Pune
6         1                                  St George's Park  Port Elizabeth
7         1                              Sheikh Zayed Stadium       Abu Dhabi
8         1                           Sharjah Cricket Stadium         Sharjah
9         1  Shaheed Veer Narayan Singh International Stadium          Raipur

In [39]:
run_sql_file(r"C:\Users\moham\OneDrive\Desktop\SEM 3 OJT\Proj_3.1\sql\05_city_fallback.sql")

ran C:\Users\moham\OneDrive\Desktop\SEM 3 OJT\Proj_3.1\sql\05_city_fallback.sql

In [40]:
q("""select city_clean from v_city_clean
where city_clean is null;""")

Empty DataFrame
Columns: [city_clean]
Index: []

In [41]:
q("""select city_clean from v_city_clean
where city_clean = 'UNKNOWN';""")

Empty DataFrame
Columns: [city_clean]
Index: []

In [42]:
q(""" SELECT city_clean FROM v_city_clean
WHERE city_clean IN('UNKNOWN');""")

Empty DataFrame
Columns: [city_clean]
Index: []

In [43]:
q(""" SELECT city_clean FROM v_city_clean
LIMIT 5;""")

  city_clean
0  Bangalore
1  Hyderabad
2       Pune
3     Rajkot
4     Indore

In [44]:
run_sql_file(r"C:\Users\moham\OneDrive\Desktop\SEM 3 OJT\Proj_3.1\sql\06_season_year.sql")

ran C:\Users\moham\OneDrive\Desktop\SEM 3 OJT\Proj_3.1\sql\06_season_year.sql

In [45]:
q(""" select season,
         count(*) as matches
from matches
where season ='2020/21'
group by season;""")

    season  matches
0  2020/21       60

In [46]:
run_sql_file(
    r"C:\Users\moham\OneDrive\Desktop\SEM 3 OJT\Proj_3.1\sql\06_season_year.sql"
)

q("""
SELECT DISTINCT season, season_year
FROM v_season
WHERE season = '2020/21';
""")

ran C:\Users\moham\OneDrive\Desktop\SEM 3 OJT\Proj_3.1\sql\06_season_year.sql

    season  season_year
0  2020/21         2020

In [47]:
run_sql_file(r"C:\Users\moham\OneDrive\Desktop\SEM 3 OJT\Proj_3.1\sql\07_win_definition.sql")

ran C:\Users\moham\OneDrive\Desktop\SEM 3 OJT\Proj_3.1\sql\07_win_definition.sql

In [48]:
run_sql_file(r"C:\Users\moham\OneDrive\Desktop\SEM 3 OJT\Proj_3.1\sql\08_matches_clean.sql")

ran C:\Users\moham\OneDrive\Desktop\SEM 3 OJT\Proj_3.1\sql\08_matches_clean.sql

In [49]:
run_sql_file(r"C:\Users\moham\OneDrive\Desktop\SEM 3 OJT\Proj_3.1\sql\08_matches_clean.sql")

q("""SELECT * from matches_clean;""")

ran C:\Users\moham\OneDrive\Desktop\SEM 3 OJT\Proj_3.1\sql\08_matches_clean.sql

,match_id,venue_clean,city_clean,season_year,result,match_winner,player_of_match,toss_decision
0,335982,M Chinnaswamy Stadium,Bangalore,2008,win,Kolkata Knight Riders,BB McCullum,field
1,1082591,Rajiv Gandhi International Stadium,Hyderabad,2017,win,Sunrisers Hyderabad,Yuvraj Singh,field
2,1082592,Maharashtra Cricket Association Stadium,Pune,2017,win,Rising Pune Supergiant,SPD Smith,field
3,1082593,Saurashtra Cricket Association Stadium,Rajkot,2017,win,Kolkata Knight Riders,CA Lynn,field
4,1082594,Holkar Cricket Stadium,Indore,2017,win,Punjab Kings,GJ Maxwell,field
...,...,...,...,...,...,...,...,...
1063,1529279,Sawai Mansingh Stadium,Jaipur,2026,win,Sunrisers Hyderabad,Ishan Kishan,field
1064,1529280,MA Chidambaram Stadium,Chennai,2026,win,Gujarat Titans,K Rabada,field
1065,1529282,Arun Jaitley Stadium,Delhi,2026,win,Royal Challengers Bangalore,JR Hazlewood,field
1066,1529284,Wankhede Stadium,Mumbai,2026,win,Sunrisers Hyderabad,H Klaasen,bat
1067,1529286,Sawai Mansingh Stadium,Jaipur,2026,win,Delhi Capitals,KL Rahul,bat

In [51]:
import ast
import pandas as pd 
d= pd.read_sql('Select * From deliveries where fielders_involved is not null', con)
d['fielders'] = d['fielders_involved'].apply(ast.literal_eval)

d=d.explode('fielders')
d['fielders'].value_counts().head(5)

AttributeError: 'Series' object has no attribute 'values_counts'